// <auto-generated />
using System;
using AnteyaSidOnContainers.Services.Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AnteyaSidOnContainers.Services.Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20210306180119_AddTradingOrder-Id")]
    partial class AddTradingOrderId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AnteyaSidOnContainers.Services.Catalog.Data.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("AnteyaSidOnContainers.Services.Catalog.Data.Models.Idempotency.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("AnteyaSidOnContainers.Services.Catalog.Data.Models.TradingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<DateTime?>("OrderCloseTime");

                    b.Property<decimal>("OrderCommission");

                    b.Property<DateTime?>("OrderExpiration");

                    b.Property<double>("OrderLots");

                    b.Property<decimal>("OrderOpenPrice");

                    b.Property<DateTime?>("OrderOpenTime");

                    b.Property<decimal>("OrderProfit");

                    b.Property<decimal>("OrderStopLoss");

                    b.Property<decimal>("OrderSwap");

                    b.Property<string>("OrderSymbol");

                    b.Property<decimal>("OrderTakeProfit");

                    b.Property<string>("OrderTicket");

                    b.Property<string>("OrderType");

                    b.Property<string>("Source");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("TradingOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
