version: '3.4'

services:
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://10.0.75.1:5105
      - CatalogUrl=http://10.0.75.1:5101
      - CallBackUrl=http://localhost:5100/
      - EventBusConnectionUrl=${EVENT_BUS_CONNECTION_URL:-amqp://hvagcwtv:nRzJYkkqmmvPmmhrpxnqSzyZsXfGi4Nu@wolverine.rmq.cloudamqp.com/hvagcwtv}
    ports:
      - "5100:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NpgConnectionString=${ANTEYA_SID_IDENTITY_DB:-User ID = postgres;Password=56;Server=192.168.1.125;Port=5432;Database=identity.db;Integrated Security=true; Pooling=true}
      - MvcClient=http://localhost:5100
    ports:
      - "5105:80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NpgConnectionString=${ANTEYA_SID_IDENTITY_DB:-User ID = postgres;Password=56;Server=192.168.1.125;Port=5432;Database=Catalog.db;Integrated Security=true; Pooling=true}
      - EventBusConnectionUrl=${EVENT_BUS_CONNECTION_URL:-amqp://hvagcwtv:nRzJYkkqmmvPmmhrpxnqSzyZsXfGi4Nu@wolverine.rmq.cloudamqp.com/hvagcwtv}
    ports:
      - "5101:80"

