version: '3.2'

services:
  webmvc:
    image: anteyasid/webmvc
    build:
      context: .
      dockerfile: src/WebApps/WebMVC/Dockerfile
    depends_on:
      - identity.api
      - catalog.api

  identity.api:
    image: anteyasid/identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  catalog.api:
    image: anteyasid/catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile