version: '3'

services:
  identity.api:
    image: anteyasid/identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  webmvc:
    image: anteyasid/webmvc
    build:
      context: .
      dockerfile: src/WebApps/WebMVC/Dockerfile

    depends_on:
      - identity.api
