version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    container_name: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./anteyaSidOnContainers.sln && dotnet publish ./anteyaSidOnContainers.sln -c Release -o ./obj/Docker/publish"
