version: '3'

services:
  identity.api:
    image: anteyasid/identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

networks:
  hostnet:
    external: true