version: '3'

services:
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://10.0.75.1:5105
      - CallBackUrl=http://localhost:5100/
    ports:
      - "5100:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NpgConnectionString=${ANTEYA_SID_IDENTITY_DB:-User ID = postgres;Password=56;Server=192.168.1.118;Port=5432;Database=identity.db;Integrated Security=true; Pooling=true}
      - MvcClient=http://localhost:5100
    ports:
      - "5105:80"
  items.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

