version: '3'

services:

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://10.0.75.1:5105
    ports:
      - "5100:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "5105:80"
