version: 2

general:
  branches:
    only:
     - master



jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
         heroku --version
         heroku update

      # build image
      - run: |
         docker info
         docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

      # print image
      - run: |
         docker images

      # deploy the image
      - run: |
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag anteyasid/identity.api registry.heroku.com/$HEROKU_IDENTITY_API_NAME/web
         docker push registry.heroku.com/$HEROKU_IDENTITY_API_NAME/web
         docker tag anteyasid/catalog.api registry.heroku.com/$HEROKU_CATALOG_API_NAME/web
         docker push registry.heroku.com/$HEROKU_CATALOG_API_NAME/web
         docker tag anteyasid/webmvc registry.heroku.com/$HEROKU_WEB_MVC_NAME/web
         docker push registry.heroku.com/$HEROKU_WEB_MVC_NAME/web

      # release images 
      - run: |
         heroku container:release web --app $HEROKU_IDENTITY_API_NAME
         heroku container:release web --app $HEROKU_CATALOG_API_NAME
         heroku container:release web --app $HEROKU_WEB_MVC_NAME
      