version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout


      # build image
      - run: |
         docker info
         docker-compose build

      # deploy the image
      - run: |
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
       
         docker tag anteyasid/webmvc registry.heroku.com/$HEROKU_WEB_MVC_NAME/web
         docker push registry.heroku.com/$HEROKU_WEB_MVC_NAME/webdocke